server:
  port: 8080

spring:
  application:
    name: master-node

zookeeper:
  connect-string: localhost:2181
  namespace: distributed-storage
  session-timeout: 60000
  connection-timeout: 15000

storage:
  base-path: /data/storage
  temp-path: /data/temp 